# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamuser',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='team.Account'),
        ),
        migrations.AlterField(
            model_name='teamuser',
            name='team',
            field=models.ManyToManyField(blank=True, null=True, related_name='team', to='team.Team'),
        ),
    ]
