# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 01:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_account_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='team_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='team_service', to='team.Service'),
        ),
        migrations.AlterField(
            model_name='teamuser',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='team', to='team.Team'),
        ),
    ]
