# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20160520_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamuser',
            name='is_temp',
            field=models.BooleanField(default=False),
        ),
    ]
