# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_teamuser_is_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamuser',
            name='team',
        ),
    ]
