# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_remove_teamuser_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
