# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_account_exp_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='exp_date',
        ),
        migrations.AddField(
            model_name='teamuser',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
