# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_auto_20160520_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamuser',
            name='last4_card_num',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
