# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_auto_20160523_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='org_name',
            field=models.CharField(default='Slack', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='team_name',
            field=models.CharField(default='Slack', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('Trello', 'Trello'), ('Github', 'Github'), ('Bitbucket', 'Bitbucket'), ('Slack', 'Slack'), ('Google Apps', 'Google Apps')], max_length=50),
        ),
    ]
