# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0013_auto_20160531_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('Trello', 'Trello'), ('Github', 'Github'), ('Bitbucket', 'Bitbucket'), ('Slack', 'Slack'), ('Google Apps', 'Google Apps'), ('Jira', 'Jira'), ('Confluence', 'Confluence'), ('HipChat', 'HipChat')], max_length=50),
        ),
    ]
